refactor(hooks): General cleanup & minor fixes

diff --git a/pre-push b/pre-push
--- a/pre-push
+++ b/pre-push
@@ -1,37 +1,38 @@
-#!/bin/bash -
+#!/bin/bash
 #===============================================================================
 #
-#          FILE: pre-push.sh
+#          FILE: pre-push
 #
-#         USAGE: ./pre-push.sh
+#         USAGE: ./pre-push
 #
-#   DESCRIPTION: 
+#   DESCRIPTION: ---
 #
 #       OPTIONS: ---
 #  REQUIREMENTS: ---
 #          BUGS: ---
 #         NOTES: ---
 #        AUTHOR: ---, 
-#  ORGANIZATION: 
+#  ORGANIZATION: ---
 #       CREATED: 09/27/2021 11:32:58 PM
-#      REVISION:  ---
+#      REVISION: 2021-10-29 15:13
 #===============================================================================
-
-set -o nounset                                  # Treat unset variables as an error
+set -o nounset
 
 function main() {
   trap endScript INT SIGINT QUIT ABRT KILL TERM STOP PWR
 
-  printf "LOADING TESTS... (this could take a while)"
-  sleep 1
+  echo "LOADING Flutter Tests... (this could take a while)"
   TEST_RESULTS=$(flutter test --no-pub)
 
-  PASSED_TESTS=$(echo $TEST_RESULTS | grep -Po "[0-9]+:[0-9]+\s\K\+[0-9]+" | tail -n1)
-  RAW_ERRORS=$(echo $TEST_RESULTS | grep -Po "[0-9]+:[0-9]+\s\+[0-9]+\s-[0-9]+:\s\K(_|\.|\/|[a-zA-Z0-9])+:(\s|[A-Za-z0-9]|,|\.|!|\\|/|\|\?|\`|\"|\'|\-)+\s\[E\]")
+  PASSED_TESTS_REGEX="(\d+):\d+\s\K\+\d+"
+  FAILED_TESTS_REGEX="\d+:\d+\s\+\d+\s-\d+:\s\K(_|\.|\/|\d|\w)+:(\s|\d|\w|,|\.|!|\\|/|\|\?|\`|\"|\'|\-)+\s\[E\]"
 
-  readarray -d "[E]" -t ERRORS <<<"$RAW_ERRORS"
+  PASSED_TESTS=$(echo $TEST_RESULTS | grep -Po $PASSED_TESTS_REGEX | tail -n1)
+  RAW_ERRORS=$(echo $TEST_RESULTS | grep -Po $FAILED_TESTS_REGEX)
 
-  [[ -z "$RAW_ERRORS" ]] && successMessage $PASSED_TESTS && exit 0
+  readarray -d "[E]" -t ERRORS <<< "$RAW_ERRORS"
+  [[ -z $PASSED_TESTS ]] && echo "Error on pubspec.yaml" && exit 1
+  [[ -z $RAW_ERRORS   ]] && successMessage $PASSED_TESTS && exit 0
 
   clear
   red && bold
@@ -48,7 +49,7 @@ function main() {
   echo -e "=-----------------------------------------------------------------------------------------------------------------------="
 
   yellow
-  echo -e "\n\n\tFix them before pushing again...\n"
+  echo -e "\n\n\tFix them before pushing again... 7_7\n"
   exit 1
 }
 
